<TonalButton@MDButton>:
    style: "tonal"
    text: ""
    theme_width: "Custom"
    theme_height: "Custom"
    size_hint_x: 1
    size_hint_y: 1
	radius: [self.height / 3, ]
	theme_elevation_level: "Custom"
	elevation_level: 0
    
    MDButtonText:
        text: root.text
        font_style: "Title"
        theme_font_size: "Custom"
		font_size: "20sp"
        pos_hint: {"center_x": .5, "center_y": .5}
		

<FilledButton@TonalButton>:
	style: "filled"

<OutlinedButton@TonalButton>:
	style: "outlined"
	
