<HomeTab>:
	name: "home"
	
	MDGridLayout:
		id: home_grid
		md_bg_color: self.theme_cls.backgroundColor
		cols: 1
		rows: 3
		spacing: "10sp"
		padding: "10sp"
		
		# Hotbar
		MDGridLayout:
			rows: 1
			cols: 5
			size_hint_y: None
			height: "30sp"
			spacing: "5sp"
			OutlinedButton:
				id: secondf
				on_release: root.toggle_2nd()
				text: "2ND"
			OutlinedButton:
				id: sci
				on_release: root.toggle_sci()
				text: "SCI"
			MDWidget:
			MDWidget:
			MDWidget:
		
		# IO section
		MDGridLayout:
			id: io_section
			rows: 3
			cols: 1
			spacing: "20sp"
			
			# Input field
			MDTextField:
				id: input_field
				use_bubble: False
				use_handles: False
				allow_copy: False
				mode: "filled"
				cursor_width: '2sp'
				font_name: "fonts/DejaVuSansMono.ttf"
				font_size: "20sp"
				MDTextFieldHintText:
					
					text: "Input"
				MDTextFieldMaxLengthText:
					max_text_length: 2000
					
			# Line helper
			MDLabel:
				id: helper_line
				text: ""
				theme_text_color: "Primary"
				halign: "left"
				size_hint_y: None
				height: "10sp"
				padding: "5sp"
				allow_selection: False
        		allow_copy: False
			# Output field
			MDTextField:
				id: output_field
				use_bubble: False
				use_handles: False
				allow_copy: False
				readonly: True
				focus: False
				mode: "filled"
				font_name: "fonts/DejaVuSansMono.ttf"
				font_size: "20sp"
				MDTextFieldHintText:
					text: "Output"
					mode: "persistent"
		
		# Keyboards
		MDGridLayout:
			rows: 2
			cols: 1
			size_hint_y: None
			height: "420sp"
			spacing: "10sp"
			
			# Controls keyboard
			MDGridLayout:
				rows: 3
				cols: 5
				spacing: "10sp"
				size_hint_y: 2/7
					
				OutlinedButton:
					text: "<<"
					on_release: root.move_home()
				OutlinedButton:
					text: "<"
					on_release: root.move_left()
				OutlinedButton:
					on_release: root.get_prev_line()
					MDButtonIcon:
				    	icon: "arrow-up"
						pos_hint: {"center_x": .5, "center_y": .5}
				OutlinedButton:
					text: ">"
					on_release: root.move_right()
				OutlinedButton:
					text: ">>"
					on_release: root.move_end()
				
				
				OutlinedButton:
					id: memr
					text: "MR"
					on_release: root.toggle_2nd("off")
				OutlinedButton:
					id: mem
					text: "M+"
					on_release: root.toggle_2nd("off")
				OutlinedButton:
					on_release: root.get_next_line()
					MDButtonIcon:
				    	icon: "arrow-down"
				    	pos_hint: {"center_x": .5, "center_y": .5}
				    
				OutlinedButton:
					on_release: root.backspace()
					MDButtonIcon:
				    	icon: "backspace"
				    	pos_hint: {"center_x": .5, "center_y": .5}
					
				OutlinedButton:
					id: clear_button
					text: "C"
					on_release: 
						root.clear()
						on_release: root.toggle_2nd("off")
					
			# Divided keyboards
			MDBoxLayout:
				orientation: "horizontal"
				cols: 2
				spacing: "10sp"
				size_hint_y: 5/7
				
				# Right keyboard
				MDGridLayout:
					rows: 5
					cols: 3
					spacing: "10sp"
					size_hint_y: 1
					size_hint_x: 3
					
					TonalButton:
						text: "7"
						on_release: root.insert_text("7")
					TonalButton:
						text: "8"
						on_release: root.insert_text("8")
					TonalButton:
						text: "9"
						on_release: root.insert_text("9")
					
					TonalButton:
						text: "4"
						on_release: root.insert_text("4")
					TonalButton:
						text: "5"
						on_release: root.insert_text("5")
					TonalButton:
						text: "6"
						on_release: root.insert_text("6")
					
					TonalButton:
						text: "1"
						on_release: root.insert_text("1")
					TonalButton:
						text: "2"
						on_release: root.insert_text("2")
					TonalButton:
						text: "3"
						on_release: root.insert_text("3")
					
					TonalButton:
						text: "0"
						on_release: root.insert_text("0")
					TonalButton:
						text: "."
						on_release: root.insert_text(".")
					TonalButton:
						text: "x10^"
						on_release: root.insert_text("e")
					
					MDWidget:
					MDWidget:
					MDWidget:
					MDWidget:
					MDWidget:
					
				# Left keyboard
				MDGridLayout:
					rows: 5
					cols: 2
					spacing: "10sp"
					size_hint_y: 1
					size_hint_x: 2
					
					FilledButton:
						text: "("
						on_release: root.insert_text("(")
					FilledButton:
						text: ")"
						on_release: root.insert_text(")")
						
					FilledButton:
						text: "*"
						on_release: root.insert_text("*")
					FilledButton:
						text: "/"
						on_release: root.insert_text("/")
						
					FilledButton:
						text: "+"
						on_release: root.insert_text("+")
					FilledButton:
						text: "-"
						on_release: root.insert_text("-")
						
					FilledButton:
						text: "^"
						on_release: root.insert_text("^")
					FilledButton:
						text: "%"
						on_release: root.insert_text("%")
					MDWidget:
					OutlinedButton:
						text: "="
						on_release: root.solve()
		
