<HomeTab>:
	name: "home"
	
	MDGridLayout:
		id: home_grid
		md_bg_color: self.theme_cls.backgroundColor
		cols: 1
		rows: 3
		spacing: "8dp"
		padding: "8dp"
		
		# Hotbar
		MDGridLayout:
			rows: 1
			cols: 5
			size_hint_y: None
			height: "30dp"
			spacing: "5dp"
			OutlinedButton:
				id: secondf
				on_release: root.toggle_2nd()
				text: "2ND"
			OutlinedButton:
				id: sci
				on_release: root.toggle_sci()
				text: "SCI"
			MDWidget:
			MDWidget:
			MDWidget:
		
		# IO section
		MDGridLayout:
			id: io_section
			rows: 3
			cols: 1
			spacing: "20dp"
			
			# Input field
			MDTextField:
				id: input_field
				use_bubble: False
				use_handles: False
				allow_copy: False
				mode: "filled"
				cursor_width: '2sp'
				font_name: "fonts/DejaVuSansMono.ttf"
				font_size: "20dp"
				MDTextFieldHintText:
					
					text: "Input"
				MDTextFieldMaxLengthText:
					max_text_length: 2000
					
			# Line helper
			MDLabel:
				id: helper_line
				text: ""
				theme_text_color: "Primary"
				halign: "left"
				size_hint_y: None
				height: "10dp"
				padding: "5dp"
				allow_selection: False
        		allow_copy: False
			# Output field
			MDTextField:
				id: output_field
				use_bubble: False
				use_handles: False
				allow_copy: False
				readonly: True
				focus: False
				mode: "filled"
				font_name: "fonts/DejaVuSansMono.ttf"
				font_size: "20dp"
				MDTextFieldHintText:
					text: "Output"
					mode: "persistent"
		
		# Keyboards
		MDGridLayout:
			rows: 9
			cols: 5
			size_hint_y: 2.4
			
			spacing: "10dp"
					
			OutlinedButton:
				text: "<<"
				on_release: root.move_home()
			OutlinedButton:
				text: "<"
				on_release: root.move_left()
			OutlinedButton:
				on_release: root.get_prev_line()
				MDButtonIcon:
			    	icon: "arrow-up"
					pos_hint: {"center_x": .5, "center_y": .5}
			OutlinedButton:
				text: ">"
				on_release: root.move_right()
			OutlinedButton:
				text: ">>"
				on_release: root.move_end()
			
			OutlinedButton:
				id: memr
				text: "MR"
				on_release: root.toggle_2nd("off")
			OutlinedButton:
				id: mem
				text: "M+"
				on_release: root.toggle_2nd("off")
			OutlinedButton:
				on_release: root.get_next_line()
				MDButtonIcon:
			    	icon: "arrow-down"
			    	pos_hint: {"center_x": .5, "center_y": .5}
			    
			OutlinedButton:
				on_release: root.backspace()
				MDButtonIcon:
			    	icon: "backspace"
			    	pos_hint: {"center_x": .5, "center_y": .5}
				
			OutlinedButton:
				id: clear_button
				text: "C"
				on_release: 
					root.clear()
					on_release: root.toggle_2nd("off")
			
			
				
			
			FilledButton:
				id: sin
				text: "sin"
			FilledButton:
				id: cos
				text: "cos"
			FilledButton:
				id: tan
				text: "tan"
			FilledButton:
				id: log
				text: "log"
				on_release: root.insert_text("log(")
			FilledButton:
				text: "ln"
				on_release: root.insert_text("ln(")
			
			FilledButton:
				text: "exp"
				on_release: root.insert_text("exp(")
			FilledButton:
				text: "nCr"
				on_release: root.insert_text("C")
			FilledButton:
				text: "nPr"
				on_release: root.insert_text("P")
			FilledButton:
				id: rt
				text: "sqrt"
			FilledButton:
				text: "!"
				on_release: root.insert_text("!")
					
			TonalButton:
				text: "π"
				on_release: root.insert_text("π")
			TonalButton:
				text: "e"
				on_release: root.insert_text("e")
			TonalButton:
				text: "ANS"
				on_release: root.insert_text("ANS")
			FilledButton:
				text: "("
				on_release: root.insert_text("(")
			FilledButton:
				text: ")"
				on_release: root.insert_text(")")
				
			
					
			TonalButton:
				text: "7"
				on_release: root.insert_text("7")
			TonalButton:
				text: "8"
				on_release: root.insert_text("8")
			TonalButton:
				text: "9"
				on_release: root.insert_text("9")
			FilledButton:
				text: "*"
				on_release: root.insert_text("*")
			FilledButton:
				text: "/"
				on_release: root.insert_text("/")
			
				
			TonalButton:
				text: "4"
				on_release: root.insert_text("4")
			TonalButton:
				text: "5"
				on_release: root.insert_text("5")
			TonalButton:
				text: "6"
				on_release: root.insert_text("6")
			FilledButton:
				text: "+"
				on_release: root.insert_text("+")
			FilledButton:
				text: "-"
				on_release: root.insert_text("-")
				
				
			TonalButton:
				text: "1"
				on_release: root.insert_text("1")
			TonalButton:
				text: "2"
				on_release: root.insert_text("2")
			TonalButton:
				text: "3"
				on_release: root.insert_text("3")
			FilledButton:
				text: "^"
				on_release: root.insert_text("^")
			FilledButton:
				text: "%"
				on_release: root.insert_text("%")
			
			TonalButton:
				text: "0"
				on_release: root.insert_text("0")
			TonalButton:
				text: "."
				on_release: root.insert_text(".")
			TonalButton:
				text: "x10^"
				on_release: root.insert_text("E")
			MDWidget:
			OutlinedButton:
				text: "="
				on_release: root.solve()	
			
					
					
			
				
			
				
			
				
			
		
